version: '3'

services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - '3000:3000'
  postgres:
    image: bitnami/postgresql:latest
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgresql_master_data:
    driver: local
